In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorial version:" + str(1000*(toc - tic)) + 'ms')

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("for loop:" + str(1000*(toc - tic)) + 'ms')

250401.5526844505
Vectorial version:1.5408992767333984ms


250401.5526844418
for loop:824.4576454162598ms


In [1]:
#Broadcasting

import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
percentage = A/cal.reshape(1, 4) * 100
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [1]:
#Python numpy vectors
import numpy as np

a = np.random.randn(5)
print(a)

[-1.140731   -0.49135541 -0.05850472 -0.42016814 -0.15201176]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[-1.140731   -0.49135541 -0.05850472 -0.42016814 -0.15201176]


In [4]:
print(np.dot(a, a.T))

1.7457689871411115


In [6]:
a = np.random.randn(5, 1)
print(a)

[[ 0.12277217]
 [-0.53465674]
 [ 0.56076995]
 [ 1.86594498]
 [ 0.89896768]]


In [7]:
print(a.T)

[[ 0.12277217 -0.53465674  0.56076995  1.86594498  0.89896768]]


In [9]:
print(np.dot(a,a.T))

[[ 0.015073   -0.06564097  0.06884694  0.2290861   0.11036821]
 [-0.06564097  0.28585783 -0.29981943 -0.99764006 -0.48063913]
 [ 0.06884694 -0.29981943  0.31446293  1.04636587  0.50411406]
 [ 0.2290861  -0.99764006  1.04636587  3.48175066  1.67742423]
 [ 0.11036821 -0.48063913  0.50411406  1.67742423  0.80814289]]


In [12]:
#Assignment Question4
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)


In [13]:
#Assignment question 5
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [14]:
#Assignment question 7
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [15]:
#Asdsignment question9
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c.shape)

(3, 3)
