In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
my_list = [1, 'Colorado', 4.7]
my_list

[1, 'Colorado', 4.7]

In [7]:
my_list[0]

1

In [8]:
my_list[-1]

4.7

In [9]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

In [11]:
my_array = np.array([2, 3, 4])
my_array

array([2, 3, 4])

In [12]:
my_array[0]

2

In [ ]:
my_list = [1, 2, 3]
my_array = np.array([1, 2, 3])

In [13]:
my_array/3

array([0.66666667, 1.        , 1.33333333])

In [14]:
 my_list/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [15]:
my_list.append('new thing')

In [16]:
my_list

[1, 'Colorado', 4.7, 'new thing']

In [17]:
my_array = np.append(my_array, 5)

In [18]:
my_array

array([2, 3, 4, 5])

In [19]:
my_dict = {'key1': 'first value', 'key2': 'second value'}
my_dict['key1']

'first value'

In [20]:
my_dict['new key'] = 'newest value'

In [21]:
my_dict

{'key1': 'first value', 'key2': 'second value', 'new key': 'newest value'}

In [22]:
my_dict['int'] = 1
my_dict

{'key1': 'first value',
 'key2': 'second value',
 'new key': 'newest value',
 'int': 1}

In [23]:
df = pd.DataFrame({'col1':range(0, 3), 'col2':range(3,6)})
df

col1  col2
0     0     3
1     1     4
2     2     5

In [26]:
df.rename(columns = {'col1':'apples', 'col2':'oranges'})


apples  oranges
0       0        3
1       1        4
2       2        5