In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#Get dimension
b.ndim

2

In [6]:
#Get the shape
b.shape

(2, 3)

In [7]:
#Get type
a.dtype

dtype('int64')

In [8]:
# Get Size
a.itemsize

8

In [9]:
# Get total size
a.nbytes

24

In [10]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get specific element
a[1, 5]

13

In [12]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specifc column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting a little more fancy
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1, 5] = 20
a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:
b = np.array([[[1,2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outide in)
b[0, 1, 1]

4

In [18]:
# Replace
b[:, 1, :] = [[9, 9, 9], [8, 8]]

ValueError: setting an array element with a sequence.

In [19]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
#Initilising different types of Arrays
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# All 1s matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [23]:
# Any other number in matrix
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [28]:
# Any other number full like
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
# Random decimal numbers
# In 4 by 2 array
np.random.rand(4,2)

array([[0.61316766, 0.40895826],
       [0.77951784, 0.12154677],
       [0.98595731, 0.96205922],
       [0.6766088 , 0.95871751]])

In [30]:
# Random integer values
np.random.randint(-4, 8, size=(3,3))

array([[-2, -2, -2],
       [ 6, -2,  4],
       [ 0, -1,  4]])

In [31]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Repeat an array
#use of axis = 0 to indicate first row
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [35]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1]= z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
#Be careful in copying arrays
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


In [37]:
#Mathematics
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [38]:
a + 2

array([3, 4, 5, 6])

In [40]:
a - 2

array([-1,  0,  1,  2])

In [41]:
a /2

array([0.5, 1. , 1.5, 2. ])

In [42]:
a * 2

array([2, 4, 6, 8])

In [43]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [44]:
a ** 2

array([ 1,  4,  9, 16])

In [48]:
#Take a sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [49]:
#Take a cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [50]:
#Linear algebra
a = np.ones((2,3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [51]:
#Find deterinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [52]:
# Statistics
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.min(stats)

1

In [55]:
np.max(stats, axis = 1)

array([3, 6])

In [57]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [58]:
#Reorganising arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [60]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
#Horizontal stack
np.hstack([v1, v2, v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
#Miscellaneous
filedata = np.genfromtxt('data.txt', delimiter=',')
filedat = filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [0]:
#Boolean masking and advanced indexing
(~((filedat > 50) & (file)))